export const projects = [
    {
        "title":"25 + 5 Clock",
        "imgUrl":"/images/clock.PNG",
        "link":"https://codepen.io/elmahdi1962/pen/poRLjRg",
        "alt":"image of pomodoro clock"
    },
    {
        "title":"Javascript Calculator",
        "imgUrl":"/images/calculator.PNG",
        "link":"https://codepen.io/elmahdi1962/pen/VwPePvv",
        "alt":"image of calculator"
    },
    {
        "title":"Drum Machine",
        "imgUrl":"/images/drummachine.PNG",
        "link":"https://codepen.io/elmahdi1962/pen/PobMYOV",
        "alt":"image of a drum pad"
    },
    {
        "title":"Simple React Markdown Previewer",
        "imgUrl":"/images/marckdown.PNG",
        "link":"https://codepen.io/elmahdi1962/pen/KKNLoNy",
        "alt":"image of the markdown app"
    },
    {
        "title":"Random Quote Machine",
        "imgUrl":"/images/quotemachine.PNG",
        "link":"https://codepen.io/elmahdi1962/pen/eYBbmGV",
        "alt":"image of a quote generated by the app"
    },
    {
        "title":"Technical Documentation Page",
        "imgUrl":"/images/documentation.PNG",
        "link":"https://codepen.io/elmahdi1962/pen/WNGraLJ",
        "alt":"image of a Documentation page"
    },
    {
        "title":"Product Landing Page",
        "imgUrl":"/images/productlandingpage.PNG",
        "link":"https://codepen.io/elmahdi1962/pen/xxEbJvQ",
        "alt":"image of Product Landing Page"
    },
    {
        "title":"Survey Form",
        "imgUrl":"/images/survey.PNG",
        "link":"https://codepen.io/elmahdi1962/pen/vYXBbNj",
        "alt":"image of a survey form"
    },
    {
        "title":"Responsive web design project #1",
        "imgUrl":"/images/responsivepage.PNG",
        "link":"https://codepen.io/elmahdi1962/pen/OJRLRNz",
        "alt":"image of the website"
    }
];